import ModeloController from './modeloController.js';

const getAll = async (req, res) => {
    ...
    res.render('vista', { datos });
}
...
const createNew = async (req, res) => {
    ...
    res.redirect('/ruta');
}
...
export default {
    getAll,
    ...
}