-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 13:08:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adoptaTuMonstruo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `adoptaTuMonstruo` ;

-- -----------------------------------------------------
-- Schema adoptaTuMonstruo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adoptaTuMonstruo` ;
USE `adoptaTuMonstruo` ;

-- -----------------------------------------------------
-- Table `adoptaTuMonstruo`.`monstruos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoptaTuMonstruo`.`monstruos` ;

CREATE TABLE IF NOT EXISTS `adoptaTuMonstruo`.`monstruos` (
  `idMonstruos` INT NOT NULL AUTO_INCREMENT,
  `nombreMonstruos` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idMonstruos`),
  UNIQUE INDEX `nombreMonstruos_UNIQUE` (`nombreMonstruos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoptaTuMonstruo`.`villanos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoptaTuMonstruo`.`villanos` ;

CREATE TABLE IF NOT EXISTS `adoptaTuMonstruo`.`villanos` (
  `idVillanos` INT NOT NULL AUTO_INCREMENT,
  `nombreVillanos` VARCHAR(200) NOT NULL,
  `tituloVillanos` VARCHAR(200) NOT NULL,
  `monstruos_idmonstruos` INT NOT NULL,
  PRIMARY KEY (`idVillanos`),
  UNIQUE INDEX `idvillanos_UNIQUE` (`idVillanos` ASC) VISIBLE,
  UNIQUE INDEX `nombreVillanos_UNIQUE` (`nombreVillanos` ASC) VISIBLE,
  UNIQUE INDEX `titulo_UNIQUE` (`tituloVillanos` ASC) VISIBLE,
  INDEX `fk_villanos_monstruos_idx` (`monstruos_idmonstruos` ASC) VISIBLE,
  CONSTRAINT `fk_villanos_monstruos`
    FOREIGN KEY (`monstruos_idmonstruos`)
    REFERENCES `adoptaTuMonstruo`.`monstruos` (`idMonstruos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoptaTuMonstruo`.`poderes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoptaTuMonstruo`.`poderes` ;

CREATE TABLE IF NOT EXISTS `adoptaTuMonstruo`.`poderes` (
  `idPoderes` INT NOT NULL AUTO_INCREMENT,
  `nombrePoderes` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPoderes`),
  UNIQUE INDEX `idpoderes_UNIQUE` (`idPoderes` ASC) VISIBLE,
  UNIQUE INDEX `nombrePoderes_UNIQUE` (`nombrePoderes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoptaTuMonstruo`.`poderesMonstruos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoptaTuMonstruo`.`poderesMonstruos` ;

CREATE TABLE IF NOT EXISTS `adoptaTuMonstruo`.`poderesMonstruos` (
  `monstruos_idMonstruos` INT NOT NULL,
  `poderes_idPoderes` INT NOT NULL,
  PRIMARY KEY (`monstruos_idMonstruos`, `poderes_idPoderes`),
  INDEX `fk_monstruos_has_poderes_poderes1_idx` (`poderes_idPoderes` ASC) VISIBLE,
  INDEX `fk_monstruos_has_poderes_monstruos1_idx` (`monstruos_idMonstruos` ASC) VISIBLE,
  CONSTRAINT `fk_monstruos_has_poderes_monstruos1`
    FOREIGN KEY (`monstruos_idMonstruos`)
    REFERENCES `adoptaTuMonstruo`.`monstruos` (`idMonstruos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_monstruos_has_poderes_poderes1`
    FOREIGN KEY (`poderes_idPoderes`)
    REFERENCES `adoptaTuMonstruo`.`poderes` (`idPoderes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
