-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 12:47:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LuchadeMonstruos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LuchadeMonstruos` ;

-- -----------------------------------------------------
-- Schema LuchadeMonstruos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LuchadeMonstruos` DEFAULT CHARACTER SET utf8 ;
USE `LuchadeMonstruos` ;

-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`Villanos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`Villanos` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`Villanos` (
  `idVillanos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  `Titulo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idVillanos`),
  UNIQUE INDEX `idVillanos_UNIQUE` (`idVillanos` ASC) VISIBLE,
  UNIQUE INDEX `Nombrel_UNIQUE` (`Nombre` ASC) VISIBLE,
  UNIQUE INDEX `Titulo_UNIQUE` (`Titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`Monstruos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`Monstruos` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`Monstruos` (
  `idMonstruos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  `idVillanoMonstruo` INT NULL,
  PRIMARY KEY (`idMonstruos`),
  UNIQUE INDEX `Monstruos_UNIQUE` (`idMonstruos` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  INDEX `idVillanoMonstruo_idx` (`idVillanoMonstruo` ASC) VISIBLE,
  CONSTRAINT `idVillanoMonstruo`
    FOREIGN KEY (`idVillanoMonstruo`)
    REFERENCES `LuchadeMonstruos`.`Villanos` (`idVillanos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`AtributosMonstruos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`AtributosMonstruos` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`AtributosMonstruos` (
  `idAtributo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAtributo`),
  UNIQUE INDEX `idAtributo_UNIQUE` (`idAtributo` ASC) VISIBLE,
  UNIQUE INDEX `Ataque_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`BonificacionVillanos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`BonificacionVillanos` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`BonificacionVillanos` (
  `idBonificacionVillanos` INT NOT NULL AUTO_INCREMENT,
  `Villanos_idVillanos` INT NOT NULL,
  `NombreBonificacion` VARCHAR(200) NOT NULL,
  `AtributosMonstruos_idAtributo` INT NOT NULL,
  `Valor` INT NOT NULL DEFAULT 10,
  PRIMARY KEY (`idBonificacionVillanos`, `Villanos_idVillanos`),
  UNIQUE INDEX `idBonificacionVillanos_UNIQUE` (`idBonificacionVillanos` ASC) VISIBLE,
  INDEX `fk_BonificacionVillanos_Villanos1_idx` (`Villanos_idVillanos` ASC) VISIBLE,
  UNIQUE INDEX `NombreBonificacion_UNIQUE` (`NombreBonificacion` ASC) VISIBLE,
  INDEX `fk_BonificacionVillanos_AtributosMonstruos1_idx` (`AtributosMonstruos_idAtributo` ASC) VISIBLE,
  CONSTRAINT `fk_BonificacionVillanos_Villanos1`
    FOREIGN KEY (`Villanos_idVillanos`)
    REFERENCES `LuchadeMonstruos`.`Villanos` (`idVillanos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BonificacionVillanos_AtributosMonstruos1`
    FOREIGN KEY (`AtributosMonstruos_idAtributo`)
    REFERENCES `LuchadeMonstruos`.`AtributosMonstruos` (`idAtributo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`Poderes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`Poderes` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`Poderes` (
  `idPoderes` INT NOT NULL AUTO_INCREMENT,
  `NombrePoderes` VARCHAR(200) NOT NULL,
  `Monstruos_idMonstruos` INT NOT NULL,
  PRIMARY KEY (`idPoderes`, `Monstruos_idMonstruos`),
  UNIQUE INDEX `idPoderes_UNIQUE` (`idPoderes` ASC) VISIBLE,
  UNIQUE INDEX `NombrePoderes_UNIQUE` (`NombrePoderes` ASC) VISIBLE,
  INDEX `fk_Poderes_Monstruos1_idx` (`Monstruos_idMonstruos` ASC) VISIBLE,
  CONSTRAINT `fk_Poderes_Monstruos1`
    FOREIGN KEY (`Monstruos_idMonstruos`)
    REFERENCES `LuchadeMonstruos`.`Monstruos` (`idMonstruos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LuchadeMonstruos`.`AtributosMonstruos_has_Monstruos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LuchadeMonstruos`.`AtributosMonstruos_has_Monstruos` ;

CREATE TABLE IF NOT EXISTS `LuchadeMonstruos`.`AtributosMonstruos_has_Monstruos` (
  `AtributosMonstruos_idAtributo` INT NOT NULL,
  `Monstruos_idMonstruos` INT NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AtributosMonstruos_idAtributo`, `Monstruos_idMonstruos`),
  INDEX `fk_AtributosMonstruos_has_Monstruos_Monstruos1_idx` (`Monstruos_idMonstruos` ASC) VISIBLE,
  INDEX `fk_AtributosMonstruos_has_Monstruos_AtributosMonstruos1_idx` (`AtributosMonstruos_idAtributo` ASC) VISIBLE,
  CONSTRAINT `fk_AtributosMonstruos_has_Monstruos_AtributosMonstruos1`
    FOREIGN KEY (`AtributosMonstruos_idAtributo`)
    REFERENCES `LuchadeMonstruos`.`AtributosMonstruos` (`idAtributo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AtributosMonstruos_has_Monstruos_Monstruos1`
    FOREIGN KEY (`Monstruos_idMonstruos`)
    REFERENCES `LuchadeMonstruos`.`Monstruos` (`idMonstruos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
