-- 100 monstruos
INSERT INTO `adoptaTuMonstruo`.`monstruos` (`nombreMonstruos`)
VALUES 
('Fofi el Destructor'),
('Pulpo Furioso'),
('Chompy el Masticón'),
('Calcetín Viviente'),
('Pepito el Terrorífico'),
('Guacamole de las Sombras'),
('Puercoespín Bailarín'),
('Pingüino Furibundo'),
('Tortilla Gigante'),
('Fluffy el Implacable'),
('Don Bigote Colosal'),
('Quesadilla Andante'),
('Lagarto en Llamas'),
('Hámster del Caos'),
('Cerdito Cósmico'),
('Gato Ninja Volador'),
('Zanahoria Enfadada'),
('Pepinillo del Infierno'),
('Helado Asesino'),
('Espátula Mortal'),
('Ratón con Antifaz'),
('Repollo Rugiente'),
('Morsa Mutante'),
('Koala del Apocalipsis'),
('Cuchara Sedienta'),
('Rana del Espacio'),
('Tiburón en Patineta'),
('Piña Vengadora'),
('Búho con Sombrero'),
('Erizo Cósmico'),
('Cabra del Vacío'),
('Mono en Bicicleta'),
('Cangrejo Malvado'),
('Burbuja Destructor'),
('Perro con Jetpack'),
('Mosquito Gigante'),
('Gusano con Bigote'),
('Pulga de Hierro'),
('Aguacate Destructor'),
('Patata del Abismo'),
('Sombrero del Terror'),
('Gallina Explosiva'),
('Dragón de Gelatina'),
('Cactus Bailarín'),
('Pingüino en Armadura'),
('Foca del Inframundo'),
('Unicornio de Madera'),
('Caracol Supersónico'),
('Zorro Galáctico'),
('Cocodrilo en Zancos'),
('Murciélago Brillante'),
('Delfín con Espadas'),
('Ratón en Malla'),
('Gallo de Neón'),
('Conejo Explosivo'),
('Elefante con Capa'),
('Burro Intergaláctico'),
('Zorro con Bufanda'),
('Dragón de Goma'),
('Tigre Psicodélico'),
('Pulpo con Sombrero'),
('Mapache del Espacio'),
('Caballo Desquiciado'),
('Tortuga Veloz'),
('Canguro del Vacío'),
('Cerdo Destructor'),
('Gallo Saltarín'),
('Oso de Azúcar'),
('Caracol Furioso'),
('Llama Psíquica'),
('Serpiente Risueña'),
('Gato con Rayos Láser'),
('Pato Nuclear'),
('Dragón del Pastel'),
('Foca Ruda'),
('Gusano Rave'),
('Ratón Samurai'),
('Panda en Triciclo'),
('Cebra Cósmica'),
('Murciélago Ruidoso'),
('Camaleón Arcoíris'),
('Perico Explosivo'),
('Cabra Psicótica'),
('Ardilla con Rayo'),
('Koala Ninja'),
('Erizo Flotante'),
('Lobo en Mallas'),
('Hipopótamo Elástico'),
('Mono Intergaláctico'),
('Zorro con Pistolas'),
('Delfín Volador'),
('Tiburón Espía'),
('Serpiente Cantante'),
('Conejo Rave'),
('Foca Risueña');

--100 villanos
INSERT INTO `adoptaTuMonstruo`.`villanos` (`nombreVillanos`, `tituloVillanos`, `monstruos_idmonstruos`)
VALUES 
('Don Calzón', 'El Amo de la Intimidación', 1),
('Señor Tentáculos', 'El Maestro del Sushi', 2),
('Capitán Mordisco', 'El Destructor de Snacks', 3),
('Rey del Algodón', 'El Conquistador de Cajones', 4),
('Pepito Jr.', 'El Heredero del Caos', 5),
('El Aguacatero', 'El Aplastador de Tortillas', 6),
('Bailador Espinoso', 'El Azote de las Fiestas', 7),
('Pingüino Real', 'El Monarca Desquiciado', 8),
('Chef Tortilla', 'El Gobernante del Sartén', 9),
('Doctor Peludo', 'El Científico Loco', 10),
('Bigotón Supremo', 'El Rey del Mostacho', 11),
('Queso Fundido', 'El Lord del Guacamole', 12),
('Flamita', 'El Guardián del Asador', 13),
('Hámster del Fin', 'El Destructor de Jaulas', 14),
('Cerdito Espacial', 'El Ladrón de Jamones', 15),
('Ninjagato', 'El Amo del Sigilo', 16),
('Zanahorio', 'El Comandante Vegetal', 17),
('Señor Pickle', 'El Creador del Apocalipsis Verde', 18),
('Conde Helado', 'El Líder del Frío', 19),
('Espátula Oscura', 'El Guardián de las Cocinas', 20),
('Ratón Enmascarado', 'El Espía de las Sombras', 21),
('Repollo Destructor', 'El As de la Ensalada', 22),
('Morsa Barítona', 'El Maestro del Jazz', 23),
('Koalalipsis', 'El Fin de los Eucaliptos', 24),
('Cuchara Sangrienta', 'El Azote de las Ollas', 25),
('Rana Astronauta', 'El Saltador Espacial', 26),
('Sharky', 'El Tiburón Radical', 27),
('Piña Suprema', 'El Dictador Tropical', 28),
('Señor Búho', 'El Sabio del Bosque', 29),
('Erizo de las Estrellas', 'El Pinchador Cósmico', 30),
('Cabra Espacial', 'El Destructor de Pastizales', 31),
('Mono Maniático', 'El Saltarín Desquiciado', 32),
('Cangrejo Destructor', 'El Pillo del Mar', 33),
('Burbuja Oscura', 'El Terror del Jabón', 34),
('Perro Jet', 'El Velocista del Aire', 35),
('Mosquito Enorme', 'El Succionador Inmortal', 36),
('Gusano Sabio', 'El Oráculo del Subsuelo', 37),
('Pulga Titánica', 'El Minúsculo Invencible', 38),
('Aguacate Supremo', 'El Rey de la Palta', 39),
('Patata Oscura', 'El Señor del Horno', 40),
('Sombrero Sombrío', 'El Maestro de la Niebla', 41),
('Gallina Explosiva', 'El Azote de los Corrales', 42),
('Dragón Gelatinoso', 'El Monstruo Dulzón', 43),
('Cactus Vengador', 'El Azote del Desierto', 44),
('Pingüino Blindado', 'El Guardián del Hielo', 45),
('Foca del Inframundo', 'El Guardián del Abismo', 46),
('Unicornio Feroz', 'El Señor de la Fantasía', 47),
('Caracol Turbo', 'El Destructor Deslizante', 48),
('Zorro de las Estrellas', 'El Explorador Cósmico', 49),
('Cocodrilo Encadenado', 'El Azote del Pantano', 50),
('Murciélago Luminoso', 'El Guardián del Crepúsculo', 51),
('Delfín Guerrero', 'El Tritón del Mar', 52),
('Ratón Acorazado', 'El Minúsculo Titan', 53),
('Gallo de Fuego', 'El Fénix de los Gallineros', 54),
('Conejo del Trueno', 'El Rápido Vengador', 55),
('Elefante con Capa', 'El Titán del Espectáculo', 56),
('Burro Galáctico', 'El Corcel Intergaláctico', 57),
('Zorro con Bufanda', 'El Caballero Elegante', 58),
('Dragón de Goma', 'El Monstruo Elástico', 59),
('Tigre Psicodélico', 'El Rey de los Colores', 60),
('Pulpo con Sombrero', 'El Monarca Marítimo', 61),
('Mapache del Espacio', 'El Piloto Intergaláctico', 62),
('Caballo Desquiciado', 'El Corcel del Caos', 63),
('Tortuga Turbo', 'El Destructor de la Lentitud', 64),
('Canguro del Abismo', 'El Guardián del Salto', 65),
('Cerdo Destructor', 'El Señor del Chicharrón', 66),
('Gallo Bailarín', 'El Azote de la Pista', 67),
('Oso Caramelo', 'El Guardián Dulzón', 68),
('Caracol Loco', 'El Espiral del Terror', 69),
('Llama Psíquica', 'El Vidente del Infierno', 70),
('Serpiente Sonriente', 'El Hipnotizador Reptante', 71),
('Gato Láser', 'El Cazador Iluminado', 72),
('Pato Explosivo', 'El Terror del Lago', 73),
('Dragón del Pastel', 'El Glotón de la Fantasía', 74),
('Foca Rebelde', 'El As del Océano', 75),
('Gusano Raver', 'El Maestro del Ritmo', 76),
('Ratón Samurai', 'El Guerrero Miniatura', 77),
('Panda en Triciclo', 'El Equilibrista del Caos', 78),
('Cebra Espacial', 'El Viajero Galáctico', 79),
('Murciélago Aturdidor', 'El Guardián Nocturno', 80),
('Camaleón Arcoíris', 'El Maestro del Camuflaje', 81),
('Perico del Trueno', 'El Orador del Viento', 82),
('Cabra Psicótica', 'El Señor de los Balidos', 83),
('Ardilla Electrica', 'El Veloz Guardián', 84),
('Koala Ninja', 'El Sombrío Trepador', 85),
('Erizo Flotante', 'El Guardián de las Alturas', 86),
('Lobo Feroz', 'El Destructor Enmascarado', 87),
('Hipopótamo Loco', 'El Coloso de las Aguas', 88),
('Mono Galáctico', 'El Destructor de Estrellas', 89),
('Zorro Armado', 'El Maestro del Sigilo', 90),
('Delfín Acrobático', 'El Piruetero de las Profundidades', 91),
('Tiburón Espía', 'El Vigilante Oceánico', 92),
('Serpiente Melodiosa', 'El Hipnotizador de Tonos', 93),
('Conejo del Rave', 'El Saltarín del Ritmo', 94),
('Foca Risueña', 'El Guardián de la Felicidad', 95),
('Rana Saltarina', 'El Explorador Interdimensional', 96),
('Pez Dragón', 'El Terror de los Ríos', 97),
('Morsa Luchadora', 'El Azote de los Glaciares', 98),
('Cerdo Mágico', 'El Hechicero del Corral', 99),
('Dragón Nebuloso', 'El Señor de la Bruma', 100);
