-- Insertar 100 poderes graciosos y divertidos
INSERT INTO `adoptaTuMonstruo`.`poderes` (`nombrePoderes`)
VALUES 
('Invisibilidad de un Solo Pie'),
('Rugido que Suena como un Kazoo'),
('Control Absoluto sobre Calcetines'),
('Dominar el Arte del Karaoke'),
('Lanzamiento de Galletas Explosivas'),
('Creación Instantánea de Gelatina'),
('Danza Hipnótica de Cadera'),
('Hacer que Llueva Helado'),
('Control Psíquico de Globos'),
('Teletransporte pero Solo hacia el Baño'),
('Transformar el Agua en Refresco'),
('Dominar el Baile del Robot'),
('Hipnosis con Mirada Tierna'),
('Manipulación de Almohadas'),
('Lanzar Pelotas de Playa a Velocidad Supersónica'),
('Atraer Gatos con el Poder de la Mente'),
('Rayo que Convierte Todo en Churros'),
('Construir Castillos de Arena a Velocidad Luz'),
('Multiplicar Chicles con un Parpadeo'),
('Causar que Todo Huela a Pizza'),
('Rayo de Cumbia Incontrolable'),
('Transformar Hojas en Dinero del Monopolio'),
('Hacer que los Zapatos Sean Súper Cómodos'),
('Crear Mini Tornados con los Dedos'),
('Invocar Patos para Causar Caos'),
('Control del Clima, Solo para Días Nublados'),
('Hacer que Todo el Mundo Baile Salsa'),
('Telequinesis de Peluches'),
('Camuflaje en Manchas de Café'),
('Lanzar Rayos de Purpurina'),
('Transformar las Sillas en Sofás'),
('Hacer que los Frijoles Sean Más Sabrosos'),
('Causar Microexplosiones de Risa'),
('Invocar Cucharas Gigantes'),
('Rayo que Hace que Todo Sepa a Chocolate'),
('Convertir Lámparas en Discos de Fiesta'),
('Lanzar Piropos en Forma de Hologramas'),
('Dominar el Arte de Hacer Globos de Chicle Gigantes'),
('Crear Sandías Instantáneas'),
('Rayo Transformador de Gatos en Gatitos'),
('Control sobre el Wi-Fi (pero con Lag)'),
('Hacer que las Almohadas Siempre Estén Frías'),
('Transformar Camisas en Camisas Hawaianas'),
('Hacer que las Plantas Bailen Reguetón'),
('Dominar el Arte del Frisbee Volador'),
('Hacer que las Botellas de Agua Sean Infinitas'),
('Invocar Guacamoles con el Pensamiento'),
('Convertir Cables en Spaghetti Cocido'),
('Lanzar Confeti a Distancia'),
('Hacer que los Desayunos Siempre Sean Pancakes'),
('Hipnotizar con Sombreros Locos'),
('Rayo que Convierte Todo en Donas'),
('Crear Zapatillas Antigravedad'),
('Manipulación de Canicas Mágicas'),
('Atraer Abejas Amistosas'),
('Control del Movimiento de las Cortinas'),
('Crear Escaleras de Nubes'),
('Causar Peinados Locos al Estornudar'),
('Hacer que los Autos Suenen como Patitos'),
('Lanzar Chorros de Jugo de Piña'),
('Control Absoluto sobre el Papel de Regalo'),
('Transformar la Arena en Palomitas'),
('Crear Corazones Flotantes con un Silbido'),
('Acelerar las siestas a la Velocidad de la Luz'),
('Convertir los Bancos en Sillas Reclineras'),
('Control de Fuegos Artificiales de Colores'),
('Crear Burbujas Irrompibles'),
('Hacer que las Galletas Nunca se Acaben'),
('Rayo que Convierte Todo en Almohadas'),
('Transformar Mesas en Mini Trampolines'),
('Crear Nubes con Forma de Perritos'),
('Hipnosis con Canciones Infantiles'),
('Hacer que las Uñas Siempre Brillen'),
('Transformar Piedras en Caramelos'),
('Lanzar Rayos de Arcoíris Cegadores'),
('Hacer que las Puertas Nunca Se Atoren'),
('Crear Aguacates con el Poder de la Risa'),
('Invocar Tortugas Bailarinas'),
('Hacer que las Bebidas Siempre Estén Frías'),
('Rayo Transformador de Sombreros en Coronas'),
('Crear Cubos de Rubik Resueltos'),
('Lanzar Rayos que Cambian el Color de las Paredes'),
('Hacer que las Camas Siempre Estén Hechas'),
('Transformar los Cojines en Ovejas de Felpa'),
('Dominar el Arte de los Peinados Locos'),
('Control Psíquico de Globos de Fiesta'),
('Hacer que las Risas Se Escuchen Más Fuertes'),
('Crear Torbellinos de Papeles de Colores'),
('Invocar Helados de Sabores Aleatorios'),
('Lanzar Rayos que Causan Cosquillas'),
('Convertir los Paraguas en Aviones de Papel'),
('Crear Guantes Invernales Automáticos'),
('Hacer que Todo el Mundo Hable en Rimas'),
('Transformar Platos Vacíos en Postres Mágicos'),
('Lanzar Rayos de Calorcito Perfecto'),
('Hacer que las Letras en los Libros Bailen');
